CC:=gcc
objects = hw0201 hw0202 hw0203 hw0204
all: 
	
	gcc -o hw0202 hw0202.c
	gcc -o hw0203 hw0203.c 
	gcc -o hw0204 hw0204.c  
	gcc -o hw0201 hw0201.c
	#gcc -o hw0205 hw0205.c

clean:
	rm -f *.o
	rm -f $(objects)
